server:
  bind: "127.0.0.1:8081"

db:
  url: "postgres://superset:superset@127.0.0.1:55432/superset"
  max_connections: 10

fetcher:
  interval_secs: 300
  batch_size: 8
  concurrency: 4
  request_timeout_secs: 15

logging:
  file: "logs/backend.log"
  level: "info"

ai:
  deepseek:
    api_key: "sk-0c8d27daaa0e41fd8e44b2603727ba3f"
    base_url: "https://api.deepseek.com"
    model: "deepseek-chat"
    timeout_secs: 30

deployment:
  app_user: "swartz"
  domain: "swartzlubel.online"
  public_api_base_url: "https://swartzlubel.online:5007/api"
  domain_aliases:
    - "localhost"
  ssl:
    cert_path: "/home/swartz/.acme.sh/swartzlubel.online_ecc/fullchain.cer"
    key_path: "/home/swartz/.acme.sh/swartzlubel.online_ecc/swartzlubel.online.key"

  paths:
    repo_root: "/home/swartz/WorkSpace/NewsAggregator"
    backend_dir: "/home/swartz/WorkSpace/NewsAggregator/backend"
    frontend_dir: "/home/swartz/WorkSpace/NewsAggregator/frontend"
    config_file: "/home/swartz/WorkSpace/NewsAggregator/config/config.yaml"

  backend:
    binary: "/home/swartz/WorkSpace/NewsAggregator/backend/target/release/backend"
    bind_addr: "127.0.0.1:8081"

  static:
    root: "/var/www/news-aggregator/dist"
    owner: "www-data"
    group: "www-data"

  nginx:
    site_name: "news-aggregator"
    conf_path: "/etc/nginx/sites-available/news-aggregator.conf"
    enabled_path: "/etc/nginx/sites-enabled/news-aggregator.conf"

  systemd:
    service_name: "news-backend.service"
    unit_path: "/etc/systemd/system/news-backend.service"

  runtime_env:
    database_url: "postgres://superset:superset@127.0.0.1:55432/superset"
    log_file_path: "/var/log/news-backend.log"
    fetch_interval_secs: 300
    fetch_batch_size: 8
    fetch_concurrency: 4
    fetch_timeout_secs: 15
    log_level: "info"
