# Example configuration for the NewsAggregator backend.
# Copy to config/config.yaml and adjust values or load via environment vars.
server:
  bind: "127.0.0.1:8081"

db:
  url: "postgres://user:pass@localhost:5432/news"
  max_connections: 10

fetcher:
  interval_secs: 300
  batch_size: 8
  concurrency: 4
  request_timeout_secs: 15

logging:
  file: "logs/backend.log"
  level: "info"

ai:
  deepseek:
    # API key can be provided via env DEEPSEEK_API_KEY instead.
    api_key: ""
    base_url: "https://api.deepseek.com"
    model: "deepseek-chat"
    timeout_secs: 30
  qdrant:
    enabled: false
    uri: "http://localhost:6334"
    api_key: ""
    collection: "news_articles"
    vector_size: 384
